<?php
namespace SakuraWf;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-05 at 16:43:53.
 */
class UtilTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Util
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Util;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers SakuraWf\Util::getLogger
     * @todo   Implement testGetLogger().
     */
    public function testGetLogger()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SakuraWf\Util::getEnumLabel
     * @todo   Implement testGetEnumLabel().
     */
    public function testGetEnumLabel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SakuraWf\Util::getEnumList
     * @todo   Implement testGetEnumList().
     */
    public function testGetEnumList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SakuraWf\Util::getLanguage
     * @todo   Implement testGetLanguage().
     */
    public function testGetLanguage()
    {
        $language = $this->object->getLanguage();
        $this->assertEquals('ja', $language);
    }

    /**
     * @covers SakuraWf\Util::startsWith
     * @todo   Implement testStartsWith().
     */
    public function testStartsWith()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SakuraWf\Util::generateInitialPassword
     * @todo   Implement testGenerateInitialPassword().
     */
    public function testGenerateInitialPassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SakuraWf\Util::getBrowser
     * @todo   Implement testGetBrowser().
     */
    public function testGetBrowser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SakuraWf\Util::getContentDisposition
     * @todo   Implement testGetContentDisposition().
     */
    public function testGetContentDisposition()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SakuraWf\Util::getValueType
     * @todo   Implement testGetValueType().
     */
    public function testGetValueType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
