<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="utf-8">
<link rel="stylesheet" href="<?php echo $this->getUrl('style.css'); ?>">
<script src="<?php echo $this->getUrl('script.js'); ?>"></script>
</head>
<body>
<form action="<?php echo $this->getUrl('login/login'); ?>" method="post">
<table>
<tr>
    <td><?php echo $this->labels['login_id']; ?></td>
    <td>
        <input type="text" name="login_id" value="<?php echo isset($_POST['login_id']) ? $_POST['login_id'] : ''; ?>">
        <span class="error"><?php echo isset($this->errors['login_id']) ? '<br>' . $this->errors['login_id'] : ''; ?></span>
    </td>
</tr>
<tr>
    <td><?php echo $this->labels['password']; ?></td>
    <td>
        <input type="password" name="password">
        <span class="error"><?php echo isset($this->errors['password']) ? '<br>' . $this->errors['password'] : ''; ?></span>
    </td>
</tr>
<tr>
    <td></td>
    <td style="text-align:right;"><input type="submit" value="<?php echo $this->labels['login']; ?>"></td>
</table>
</form>
</body>
</html>
